FROM php:7.4-apache

# Permisões 
RUN chown -R root:www-data /var/www/html
RUN chmod u+rwx,g+rx,o+rx /var/www/html
RUN find /var/www/html -type d -exec chmod u+rwx,g+rx,o+rx {} +
RUN find /var/www/html -type f -exec chmod u+rw,g+rw,o+r {} +

# .htaccess
RUN a2enmod rewrite
#ssl 
RUN a2enmod ssl